{
"XXXXXXXXXXXXXXXXXXX",
"X   A  X   X  A   X",
"X XX X X X X X XX X",
"XA  AX  AXA  XA  AX",
"X XX XXX X XXX XX X",
"X X A A  X  A A X X",
"X X XX XXXXX XX X X",
" A AA A  F  A AA A ",
"X XX X XDDDX X XX X",
"X XX X XFFFX X XX X",
"XA  AX XXXXX XA  AX",
"X XX XA     AX XX X",
"X  X X XXXXX X X  X",
"XX XA A  X  A AX XX",
" A X XXX X XXX X A ",
"X XX X   XA  X XX X",
"XA A X XA AX X A AX",
"X X XX X X X XX X X",
"X X   AX   XA   X X",
"X XXXX XXXXX XXXX X",
"XC    A     A     X",
"XXXXXXXXXXXXXXXXXXX"
};